//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.13.1
//     from Assets/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/PlayerInput.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @PlayerInput: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""vrInput"",
            ""id"": ""0d24efcc-8a86-4d86-bfb6-d5cab63a2d91"",
            ""actions"": [
                {
                    ""name"": ""LeftHandDrawing"",
                    ""type"": ""Value"",
                    ""id"": ""e0a6a59e-6ff6-4f23-a816-7ae331cf21bc"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightHandDrawing"",
                    ""type"": ""Value"",
                    ""id"": ""b40248db-c778-42ba-8ba4-55a09fdb07e3"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightPinch"",
                    ""type"": ""Value"",
                    ""id"": ""0cdff918-561a-4b35-904a-52c6d2c45b60"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LeftPinch"",
                    ""type"": ""Value"",
                    ""id"": ""fb4c121a-21cf-43f2-9a7f-dbfd91181d27"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4cf8deb9-40f3-47fa-ad18-e4fba4dfe15c"",
                    ""path"": ""<XRController>{LeftHand}/{Trigger}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftHandDrawing"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d5492575-bfb9-425b-83cf-9ddb724cb83a"",
                    ""path"": ""<XRController>{RightHand}/{Trigger}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightHandDrawing"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""50b69f31-be9b-4c7c-9535-2fe4f3619988"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightPinch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ec919689-7691-472b-ab53-c10cff01615d"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftPinch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // vrInput
        m_vrInput = asset.FindActionMap("vrInput", throwIfNotFound: true);
        m_vrInput_LeftHandDrawing = m_vrInput.FindAction("LeftHandDrawing", throwIfNotFound: true);
        m_vrInput_RightHandDrawing = m_vrInput.FindAction("RightHandDrawing", throwIfNotFound: true);
        m_vrInput_RightPinch = m_vrInput.FindAction("RightPinch", throwIfNotFound: true);
        m_vrInput_LeftPinch = m_vrInput.FindAction("LeftPinch", throwIfNotFound: true);
    }

    ~@PlayerInput()
    {
        UnityEngine.Debug.Assert(!m_vrInput.enabled, "This will cause a leak and performance issues, PlayerInput.vrInput.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // vrInput
    private readonly InputActionMap m_vrInput;
    private List<IVrInputActions> m_VrInputActionsCallbackInterfaces = new List<IVrInputActions>();
    private readonly InputAction m_vrInput_LeftHandDrawing;
    private readonly InputAction m_vrInput_RightHandDrawing;
    private readonly InputAction m_vrInput_RightPinch;
    private readonly InputAction m_vrInput_LeftPinch;
    /// <summary>
    /// Provides access to input actions defined in input action map "vrInput".
    /// </summary>
    public struct VrInputActions
    {
        private @PlayerInput m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public VrInputActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "vrInput/LeftHandDrawing".
        /// </summary>
        public InputAction @LeftHandDrawing => m_Wrapper.m_vrInput_LeftHandDrawing;
        /// <summary>
        /// Provides access to the underlying input action "vrInput/RightHandDrawing".
        /// </summary>
        public InputAction @RightHandDrawing => m_Wrapper.m_vrInput_RightHandDrawing;
        /// <summary>
        /// Provides access to the underlying input action "vrInput/RightPinch".
        /// </summary>
        public InputAction @RightPinch => m_Wrapper.m_vrInput_RightPinch;
        /// <summary>
        /// Provides access to the underlying input action "vrInput/LeftPinch".
        /// </summary>
        public InputAction @LeftPinch => m_Wrapper.m_vrInput_LeftPinch;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_vrInput; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="VrInputActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(VrInputActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="VrInputActions" />
        public void AddCallbacks(IVrInputActions instance)
        {
            if (instance == null || m_Wrapper.m_VrInputActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_VrInputActionsCallbackInterfaces.Add(instance);
            @LeftHandDrawing.started += instance.OnLeftHandDrawing;
            @LeftHandDrawing.performed += instance.OnLeftHandDrawing;
            @LeftHandDrawing.canceled += instance.OnLeftHandDrawing;
            @RightHandDrawing.started += instance.OnRightHandDrawing;
            @RightHandDrawing.performed += instance.OnRightHandDrawing;
            @RightHandDrawing.canceled += instance.OnRightHandDrawing;
            @RightPinch.started += instance.OnRightPinch;
            @RightPinch.performed += instance.OnRightPinch;
            @RightPinch.canceled += instance.OnRightPinch;
            @LeftPinch.started += instance.OnLeftPinch;
            @LeftPinch.performed += instance.OnLeftPinch;
            @LeftPinch.canceled += instance.OnLeftPinch;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="VrInputActions" />
        private void UnregisterCallbacks(IVrInputActions instance)
        {
            @LeftHandDrawing.started -= instance.OnLeftHandDrawing;
            @LeftHandDrawing.performed -= instance.OnLeftHandDrawing;
            @LeftHandDrawing.canceled -= instance.OnLeftHandDrawing;
            @RightHandDrawing.started -= instance.OnRightHandDrawing;
            @RightHandDrawing.performed -= instance.OnRightHandDrawing;
            @RightHandDrawing.canceled -= instance.OnRightHandDrawing;
            @RightPinch.started -= instance.OnRightPinch;
            @RightPinch.performed -= instance.OnRightPinch;
            @RightPinch.canceled -= instance.OnRightPinch;
            @LeftPinch.started -= instance.OnLeftPinch;
            @LeftPinch.performed -= instance.OnLeftPinch;
            @LeftPinch.canceled -= instance.OnLeftPinch;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="VrInputActions.UnregisterCallbacks(IVrInputActions)" />.
        /// </summary>
        /// <seealso cref="VrInputActions.UnregisterCallbacks(IVrInputActions)" />
        public void RemoveCallbacks(IVrInputActions instance)
        {
            if (m_Wrapper.m_VrInputActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="VrInputActions.AddCallbacks(IVrInputActions)" />
        /// <seealso cref="VrInputActions.RemoveCallbacks(IVrInputActions)" />
        /// <seealso cref="VrInputActions.UnregisterCallbacks(IVrInputActions)" />
        public void SetCallbacks(IVrInputActions instance)
        {
            foreach (var item in m_Wrapper.m_VrInputActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_VrInputActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="VrInputActions" /> instance referencing this action map.
    /// </summary>
    public VrInputActions @vrInput => new VrInputActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "vrInput" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="VrInputActions.AddCallbacks(IVrInputActions)" />
    /// <seealso cref="VrInputActions.RemoveCallbacks(IVrInputActions)" />
    public interface IVrInputActions
    {
        /// <summary>
        /// Method invoked when associated input action "LeftHandDrawing" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLeftHandDrawing(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RightHandDrawing" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRightHandDrawing(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RightPinch" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRightPinch(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LeftPinch" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLeftPinch(InputAction.CallbackContext context);
    }
}
